name: flutter_recruitment_task
description: Flutter recruitment task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: 3.3.9

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  get_it: ^7.2.0
  go_router: ^6.0.2
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Translations
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/generated
